FROM node:18-bullseye-slim AS builder
WORKDIR /app

# Declare ALL build-time env vars
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG NEXT_PUBLIC_TYPESENSE_API_KEY
ARG NODE_ENV
ARG NEXT_PUBLIC_MODEL_PATH
ARG TRANSFORMERS_CACHE
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_MFCO_API_USERNAME
ARG NEXT_PUBLIC_MFCO_API_PASSWORD
ARG NEXT_PUBLIC_MAX_FILE_SIZE
ARG NEXT_PUBLIC_ALLOWED_FILE_TYPES
ARG SESSION_TIMEOUT
ARG NEXT_PUBLIC_TYPESENSE_SEARCH_KEY
ARG NEXT_PUBLIC_TYPESENSE_HOST
ARG NEXT_PUBLIC_TYPESENSE_PORT
ARG NEXT_PUBLIC_TYPESENSE_PROTOCOL

# Install required system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    python3 \
    libc6 \
    && rm -rf /var/lib/apt/lists/*

COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:18-bullseye-slim AS runner
WORKDIR /app

# Declare ALL runtime env vars
ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY
ENV NEXT_PUBLIC_TYPESENSE_API_KEY=$NEXT_PUBLIC_TYPESENSE_API_KEY
ENV NODE_ENV=production
ENV NEXT_PUBLIC_MODEL_PATH=$NEXT_PUBLIC_MODEL_PATH
ENV TRANSFORMERS_CACHE=$TRANSFORMERS_CACHE
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_MFCO_API_USERNAME=$NEXT_PUBLIC_MFCO_API_USERNAME
ENV NEXT_PUBLIC_MFCO_API_PASSWORD=$NEXT_PUBLIC_MFCO_API_PASSWORD
ENV NEXT_PUBLIC_MAX_FILE_SIZE=$NEXT_PUBLIC_MAX_FILE_SIZE
ENV NEXT_PUBLIC_ALLOWED_FILE_TYPES=$NEXT_PUBLIC_ALLOWED_FILE_TYPES
ENV SESSION_TIMEOUT=$SESSION_TIMEOUT
ENV NEXT_PUBLIC_TYPESENSE_SEARCH_KEY=$NEXT_PUBLIC_TYPESENSE_SEARCH_KEY
ENV NEXT_PUBLIC_TYPESENSE_HOST=$NEXT_PUBLIC_TYPESENSE_HOST
ENV NEXT_PUBLIC_TYPESENSE_PORT=$NEXT_PUBLIC_TYPESENSE_PORT
ENV NEXT_PUBLIC_TYPESENSE_PROTOCOL=$NEXT_PUBLIC_TYPESENSE_PROTOCOL

# Install only the required runtime dependencies
RUN apt-get update && apt-get install -y \
    libc6 \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /app/package*.json ./
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/node_modules ./node_modules

EXPOSE 3000
CMD ["npm", "start"] 